### ISSUE TITLE
OOM issue with RedissonExecutorService

### ISSUE THREAD

**Issue by yjain3326** [redisson/redisson#1158]
Hi,

We are seeing out of memory when trying to use RedissonExecutorService. 
Please find attached the file you can use to reproduce the issue.
Usage:
nohup java -Xmx512m -XX:MaxMetaspaceSize=80m -cp testredisscheduler-1.0-SNAPSHOT-jar-with-dependencies.jar com.test.redis.scheduler.TestRedisScheduler 120 10 10 > output.log &

Running it for about 20-30 min produces the issue.

[final.zip](https://github.com/redisson/redisson/files/1493727/final.zip)

**Comment by mrniko** [comment]
Hi, I'll investigate this

**Comment by mrniko** [comment]
Fixed! Thanks for report

**Comment by yjain3326** [comment]
@mrniko is there a snapshot version I could try?

**Comment by mrniko** [comment]
@yjain3326 I'm afraid no. You should build it from master branch.

**Comment by yjain3326** [comment]
@mrniko I took the latest from master and used the same test code shared before but I still see the OOM exception happening.

Here are some of the Objects with biggest size and count accumulating:

<img width="1429" alt="screen shot 2017-11-23 at 13 39 34" src="https://user-images.githubusercontent.com/25619540/33189116-aee286b6-d054-11e7-9aee-c16861ba13d3.png">

**Comment by mrniko** [comment]
does your current test differ from code you shared in this task https://github.com/redisson/redisson/issues/1150 ?

**Comment by yjain3326** [comment]
@mrniko it’s the zip file I shared with this issue, final.zip above.

**Comment by mrniko** [comment]
Could you please share final version of source code, preferably in one file?

**Comment by mrniko** [comment]
@yjain3326 I did yet another optimization. Please give it a try

**Comment by yjain3326** [comment]
@mrniko Tired it, I still see the same issue.
Here is the instance size of recorded objects.
<img width="1436" alt="screen shot 2017-11-24 at 12 00 19" src="https://user-images.githubusercontent.com/25619540/33222837-16ae16ce-d10f-11e7-858a-acb0a7a19211.png">

**Comment by mrniko** [comment]
Could you combine source into single java class and share it?

**Comment by yjain3326** [comment]
@mrniko 
Main Class:
[TestRedisScheduler.txt](https://github.com/redisson/redisson/files/1502851/TestRedisScheduler.txt)

The Runnable Class:
[RedisRunner.txt](https://github.com/redisson/redisson/files/1502850/RedisRunner.txt)

**Comment by mrniko** [comment]
Hi! I have reduced String objects allocations, but can't do anything Promises objects allocations. Redisson creates Future object per `scheduleAsync` method invocation and it remains in memory till the moment of task execution.

**Comment by yjain3326** [comment]
@mrniko but even after the task are being executed the memory is not getting free up.
In the example I shared all the task are scheduled to be executed in 10 sec.

**Comment by mrniko** [comment]
You were right memory leak caused by ScheduledFuture objects. Now they are getting free up in correct way. Fixed.

**Comment by yjain3326** [comment]
@mrniko Thanks for the fix. I just tried it with my test and seems to be fine now, no memory leak observed.
I had a question around our specific use case.
Our use case is scheduling events 12hours in future with almost 2000 request per second. You mentioned that object remain in memory until they are executed. So do you think with our use case at this scale this solution would scale as I think it might then accumulate like 86million object in memory.
It would be great if you provide some suggestion on this.

**Comment by yjain3326** [comment]
@mrniko Thanks for fixing the bug. I think this is a great solution for short time scheduling, but with longer schedule period it seems to occupy memory and eventually will get OOM error.

I just tried with scheduling events 1hr in future and I got OOM in around 15min, with the above test case.

**Comment by mrniko** [comment]
I have optimized memory consumption last time and opened a new task related to this problem - https://github.com/redisson/redisson/issues/1185

**Comment by yjain3326** [comment]
@mrniko Thanks!

**Comment by yjain3326** [comment]
@mrniko When are these changes going to be released?
