### ISSUE TITLE
changeMaster failed cuase constantly "RedisTimeoutException: Unable to get connection"

### ISSUE THREAD

**Issue by empty117** [redisson/redisson#1839]
### Expected behavior

Master connection pool can be re-established later even if participal changemaster failed in redisson.

### Actual behavior

If participal changemaster failed,  then always throw "RedisTimeoutException: Unable to get connection" and cannot be recoverred.  And seems there are two masterEntry target to both old and new master address.

2019-01-07-T05:41:34.523+0200 | redisson-netty-1-2 | ERROR | org.redisson.connection.SingleEntry | Can't change master to: redis://[2a00:8a00:4000:20c::87:ace]:6379
2019-01-07-T05:44:41.319+0200 | redisson-netty-1-1 | INFO  | org.redisson.connection.pool.MasterPubSubConnectionPool | 1 connections initialized for 2a00:8a00:4000:20c::87:ace/2a00:8a00:4000:20c:0:0:87:ace:6379
2019-01-07-T05:44:41.320+0200 | redisson-netty-1-2 | INFO  | org.redisson.connection.pool.MasterConnectionPool | 32 connections initialized for 2a00:8a00:4000:20c::87:ace/2a00:8a00:4000:20c:0:0:87:ace:6379
2019-01-07-T05:44:41.331+0200 | redisson-netty-1-2 | INFO  | org.redisson.connection.SingleEntry | master 2a00:8a00:4000:20c::87:acf/2a00:8a00:4000:20c:0:0:87:acf:6379 has changed to 2a00:8a00:4000:20c::87:ace/2a00:8a00:4000:20c:0:0:87:ace:6379
2019-01-07-T05:44:43.781+0200 | register-consumer | ERROR | RegisterConsumer | Exception when consume registration/unregistration task
org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@1822f118, freeConnectionsAmount=32, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@64a6870d, freezed=false, freezeReason=null, client=[addr=redis://[2a00:8a00:4000:20c::87:acf]:6379], nodeType=MASTER, firstFail=0]]], command: (BLPOP), command params: [register-queue, 10] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:532) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[?:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[?:?]
2019-01-07-T05:44:53.981+0200 | thread-14492 | ERROR | TEST | General reason ::		
org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@6dd14177, freeConnectionsAmount=32, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@db605f5, freezed=false, freezeReason=null, client=[addr=redis://[2a00:8a00:4000:20c::87:ace]:6379], nodeType=MASTER, firstFail=0]]], command: (EVAL), command params: [local value = redis.call('hget', KEYS[1], ARGV[2]); if value == false then return nil; end; local t,..., 5, NE3SWS-NeInfo, redisson__timeout__set:{Info}, redisson__idle__set:{Info}, redisson__map_cache__last_access__set:{Info}, {Info}:redisson_options, 1546832687609, PooledUnsafeDirectByteBuf(ridx: 0, widx: 20, cap: 256)] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:532) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[?:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

### Steps to reproduce or test case

If any changeMaster activity failed and got "Can't change master to: redis://[2a00:8a00:4000:20c::87:ace]:6379" error, then masterConnection pool will not able to get connection in later phase even master connection recoverred.

### Redis version

any

### Redisson version

3.7.0

### Redisson configuration

3 sentinels + 1 master + 1 slave

**Comment by mrniko** [comment]
Fixed! thanks for report

**Comment by empty117** [comment]
I have doubts about this fix:

"currentMaster" in SentinelConnectionManager has still been changed to newMaster even it's failed. i suppose "currentMaster" shouldn't be changed, so that next round changeMaster can try to change again.

Am not sure if my understanding is correct.

**Comment by mrniko** [comment]
@empty117 

Right! Thanks for pointing out. I did some changes regarding this

**Comment by empty117** [comment]
@mrniko :+1: :  thanks.

**Comment by empty117** [comment]
I applied this change and did a check, below error still happen when "Unable to get connection" error already occured(make the master cannot be conntected for some time). Even changeMaster success, but the RedisClient in Nodescoure is still null.(Meanwhile, you can see the connections in MasterSlaveEntry are correct, and freeConnectionCount=32 as default init number).


2019-01-22-T03:48:55.050+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.pool.MasterPubSubConnectionPool | 1 connections initialized for 10.10.10.11:6379
2019-01-22-T03:48:55.062+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.pool.MasterConnectionPool | 32 connections initialized for 10.10.10.11:6379
2019-01-22-T03:48:55.065+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.SingleEntry | master 10.10.10.10:6379 has changed to 10.10.10.11:6379
2019-01-22-T03:49:20.431+0200  | myThread | ERROR | test | Exception when write to Redis:
org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, **redisClient=null**, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConn
ectionsCounter=org.redisson.pubsub.AsyncSemaphore@2174330f, **freeConnectionsAmount=32**, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@7e90a2b8, freezed=false, freezeReason=null, **client=[addr=redis://10.10.10.11:6379]**, nodeType=MASTER, firstFail=0]]], command: (BLPOP), command params: [test-queue, 10] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:532) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[?:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by empty117** [comment]
I applied this change and did a check, below error still happen when "Unable to get connection" error already occured(In my test ENV, Redis become all slaves and recoverred later). Even changeMaster success, but the RedisClient in Nodescoure is still null.(Meanwhile, you can see the connections in MasterSlaveEntry are correct, and freeConnectionCount=32 as default init number).


_2019-01-22-T03:48:55.050+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.pool.MasterPubSubConnectionPool | 1 connections initialized for 10.10.10.11:6379
2019-01-22-T03:48:55.062+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.pool.MasterConnectionPool | 32 connections initialized for 10.10.10.11:6379
2019-01-22-T03:48:55.065+0200  | redisson-netty-1-1 | INFO  | org.redisson.connection.SingleEntry | master 10.10.10.10:6379 has changed to 10.10.10.11:6379
2019-01-22-T03:49:20.431+0200  | myThread | ERROR | test | Exception when write to Redis:
org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, **redisClient=null**, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConn
ectionsCounter=org.redisson.pubsub.AsyncSemaphore@2174330f, **freeConnectionsAmount=32**, freeConnectionsCounter=org.redisson.pubsub.AsyncSemaphore@7e90a2b8, freezed=false, freezeReason=null, **client=[addr=redis://10.10.10.11:6379]**, nodeType=MASTER, firstFail=0]]], command: (BLPOP), command params: [test-queue, 10] after 3 retry attempts
        at org.redisson.command.CommandAsyncService$8.run(CommandAsyncService.java:532) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:668) ~[?:?]
        at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:743) ~[?:?]
        at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:471) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]_

**Comment by mrniko** [comment]
I can recheck it with 3.10.1 only. Please try it

**Comment by empty117** [comment]
> @empty117
> 
> I can recheck it with 3.10.1 only. Please try it

I just notice 3.10.1 has been published, i will try this version and let you know if it can be reproduce

**Comment by empty117** [comment]
> @empty117
> 
> I can recheck it with 3.10.1 only. Please try it

I tested with 3.10.1, seems it works fine, thanks for great support.
