### ISSUE TITLE
RedisTimeoutException: Unable to get connection

### ISSUE THREAD

**Issue by hlms** [redisson/redisson#1883]
### Expected behavior
Should work without any exception.

### Actual behavior
Getting the following exception intermittently:
```
WARN  - org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=32, freeConnectionsCounter=128, freezed=false, freezeReason=null, client=[addr=redis://my.server.2.1.com:6379], nodeType=MASTER, firstFail=0]]], command: (INCR), command params: [mycommand:params] after 3 retry attempts org.redisson.client.RedisTimeoutException: Unable to get connection! Node source: NodeSource [slot=null, addr=null, redisClient=null, redirect=null, entry=MasterSlaveEntry [masterEntry=[freeSubscribeConnectionsAmount=1, freeSubscribeConnectionsCounter=50, freeConnectionsAmount=32, freeConnectionsCounter=128, freezed=false, freezeReason=null, client=[addr=redis://my.server.2.1.com:6379], nodeType=MASTER, firstFail=0]]], command: (INCR), command params: [mycommand:params] after 3 retry attempts
	at org.redisson.command.CommandAsyncService$10.run(CommandAsyncService.java:703) ~[redisson-2.14.1.jar:?]
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:670) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:745) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:473) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
### Steps to reproduce or test case
I have no idea when this occurs.

### Redis version
4.0.11

### Redisson version
2.14.1

### Redisson configuration
ReplicatedServers. Please let me know if any specific setting is required.

What are the possible reasons for this exception? How to fix this?

Well, we don't have too much load on the servers.

**Comment by mrniko** [comment]
Do you see any failover prior this issue?
Could you provide full Redisson configuration?

**Comment by hlms** [comment]
Full redisson configuration:

```json
{
	"replicatedServersConfig": {
		"idleConnectionTimeout": 10000,
		"pingTimeout": 1000,
		"connectTimeout": 10000,
		"timeout": 10000,
		"retryAttempts": 3,
		"retryInterval": 1500,
		"subscriptionsPerConnection": 5,
		"sslEnableEndpointIdentification": true,
		"sslProvider": "JDK",
		"pingConnectionInterval": 0,
		"keepAlive": false,
		"tcpNoDelay": false,
		"loadBalancer": {
			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
		},
		"slaveConnectionMinimumIdleSize": 32,
		"slaveConnectionPoolSize": 64,
		"failedSlaveReconnectionInterval": 3000,
		"failedSlaveCheckInterval": 180000,
		"masterConnectionMinimumIdleSize": 32,
		"masterConnectionPoolSize": 64,
		"readMode": "MASTER_SLAVE",
		"subscriptionMode": "MASTER",
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 50,
		"dnsMonitoringInterval": 5000,
		"nodeAddresses": [
			"redis://my.server.1:6379",
			"redis://my.server.2:6379"
		],
		"scanInterval": 2000,
		"database": 0,
		"slaveSubscriptionConnectionPoolSize": 50,
		"slaveSubscriptionConnectionMinimumIdleSize": 1
	},
	"threads": 0,
	"nettyThreads": 0,
	"referenceCodecProvider": {
		"class": "org.redisson.codec.DefaultReferenceCodecProvider"
	},
	"referenceEnabled": true,
	"transportMode": "NIO",
	"lockWatchdogTimeout": 30000,
	"keepPubSubOrder": true,
	"useScriptCache": false,
	"addressResolverGroupFactory": {
		"class": "org.redisson.connection.DnsAddressResolverGroupFactory"
	},
	"useLinuxNativeEpoll": false
}
```

**Comment by hlms** [comment]
By the way, I got the redisson config by the following method:
```java
String jsonFormat = config.toJSON();
LOG.info("Redisson config in jsonFormat: " + jsonFormat);
```
Any other way to get the redisson config?

**Comment by mrniko** [comment]
@hlms 

You're right. I'll add a tip with settings could be tried to tune to overcome this issue.

**Comment by mrniko** [comment]
Done

**Comment by hlms** [comment]
@mrniko ,  
Tip is great.
My original question is when `details.getException() == null` occurs, how can we say "Unable to get connection!"  ?

Can't it be some other issue?
Does it purely mean that redisson client didn't get connection from connection pool in the client itself? or from redis server itself?

**Comment by mrniko** [comment]
@hlms 

If you look into the code there are couldn't be other errors except this one. If there are no exception then it means that connection is still hasn't been acquired from connection pool.

**Comment by hlms** [comment]
Even after fixing the failover, we are still getting this exception.

Well, we are not setting netty threads explicitly so it will create current_processors_amount * 2 netty threads.
We noticed that no application threads were attempting to read/write from/to redis.

Is it possible that the netty threads which are killed due to idle state time out get created never?
How can this be root caused?

Redisson configuration is as follows:

```json
{
	"replicatedServersConfig": {
		"idleConnectionTimeout": 10000,
		"pingTimeout": 1000,
		"connectTimeout": 10000,
		"timeout": 10000,
		"retryAttempts": 3,
		"retryInterval": 1500,
		"subscriptionsPerConnection": 5,
		"sslEnableEndpointIdentification": true,
		"sslProvider": "JDK",
		"pingConnectionInterval": 0,
		"keepAlive": false,
		"tcpNoDelay": false,
		"loadBalancer": {
			"class": "org.redisson.connection.balancer.RoundRobinLoadBalancer"
		},
		"slaveConnectionMinimumIdleSize": 32,
		"slaveConnectionPoolSize": 64,
		"failedSlaveReconnectionInterval": 3000,
		"failedSlaveCheckInterval": 180000,
		"masterConnectionMinimumIdleSize": 32,
		"masterConnectionPoolSize": 64,
		"readMode": "MASTER_SLAVE",
		"subscriptionMode": "MASTER",
		"subscriptionConnectionMinimumIdleSize": 1,
		"subscriptionConnectionPoolSize": 50,
		"dnsMonitoringInterval": 5000,
		"nodeAddresses": [
			"redis://my.server.1:6379",
			"redis://my.server.2:6379"
		],
		"scanInterval": 2000,
		"database": 0,
		"slaveSubscriptionConnectionPoolSize": 50,
		"slaveSubscriptionConnectionMinimumIdleSize": 1
	},
	"threads": 0,
	"nettyThreads": 0,
	"referenceCodecProvider": {
		"class": "org.redisson.codec.DefaultReferenceCodecProvider"
	},
	"referenceEnabled": true,
	"transportMode": "NIO",
	"lockWatchdogTimeout": 30000,
	"keepPubSubOrder": true,
	"useScriptCache": false,
	"addressResolverGroupFactory": {
		"class": "org.redisson.connection.DnsAddressResolverGroupFactory"
	},
	"useLinuxNativeEpoll": false
}
```

**Comment by mrniko** [comment]
> Is it possible that the netty threads which are killed due to idle state time out get created never?

No, but you can easily spot it if you count all threads with `redisson-netty` prefix.

By the way, do you use RBatch object?

**Comment by hlms** [comment]
We are not using RBatch object.
We are using RMap.putAll() and RLocalCachedMap.

**Comment by mrniko** [comment]
@hlms 

`RMap.putAll` execution time depends on data amount passed as parameter. Many invocations of such method with big data amount can cause this error either, since each of them consume connection.

**Comment by sgomaa** [comment]
i am getting this error
org.redisson.client.RedisTimeoutException: Unable to get connection! Try to increase 'nettyThreads' and 'connection pool' settings or set decodeInExecutor = true and increase 'threads' settingNode source: NodeSource [slot=15274, addr=redis://10.183.127.23:6380, redisClient=null, redirect=MOVED, entry=null] after 3 retry attempts
at org.redisson.command.CommandBatchService$3.run(CommandBatchService.java:673)
at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)

and i am using RBatch with version 3.11.2 
@mrniko is this related to connection leakage problem (cluster with Rbatch witn high load)

**Comment by mrniko** [comment]
@sgomaa 

Did you try to increase connection pool size? Usually Batch processing takes more time for processing due to result size and thus time of connection usage is increasing.

**Comment by sgomaa** [comment]
- @mrniko the problem it that when i get this error the app will not work until I restart it , is this is related to this issue https://github.com/redisson/redisson/issues/2587 ?
-  when i execute batch containing a lot of getBucket().get() how many connections does the batch.execute() need (what is the equation) as I am running with the default configuration version 3.11.2
- In the above error t [slot=15274, addr=redis://10.183.127.23:6380, redisClient=null, redirect=MOVED, **entry**=null]  why the entry is **NULL** ? does this mean that redis cluster node is down ?

**Comment by mrniko** [comment]
redirect=MOVED means that Redis node serves 15274 slots sends redirect to redis://10.183.127.23:6380. Check if your Redis cluster config is correct. Is there any code sample to reproduce this?

**Comment by sgomaa** [comment]
@mrniko the problem happens on the production randomly and the only solutions is to restart the app , i found that there are many connection established on client list (redis server) every 24 connection has same age (as i am using default config 24 connection) , these means that client randomly recreates new connections and the old ones are zombie connection , does shutdown() help in closing these connections or the are lost and i have to kill the app to close them ? 
should I upgrade to 3.12.x ?

**Comment by mrniko** [comment]
@sgomaa 

> these means that client randomly recreates new connections and the old ones are zombie connection

Did you try to set `pingConnectionInterval` setting?

**Comment by sgomaa** [comment]
@mrniko what pingConnectionInterval will do , and would shutdown() will kill all zombie connections ?

**Comment by mrniko** [comment]
non responsible connections will be closed automatically and reconnected

**Comment by nishubin** [comment]
Hi, have you solved this problem?
I have the same problem in production。

Redisson version
3.9.1
