### ISSUE TITLE
Deadlock after Redis timeout

### ISSUE THREAD

**Issue by hmagarotto** [redisson/redisson#1966]
### Expected behavior

After a Redis response timeout, Redisson needs to be resilient and back to normal operation after Redis timeout and allow to lock and unlock critical sections again.

### Actual behavior

After a Redis response timeout **between attempts**, Redisson adds the lock to scheduled renew task and never remove them. So, the application enters on a deadlock due to a lock renewed even after unlock.
The task can run on the same thread due to reentrant lock feature, but when the task runs on another thread a deadlock occurs.

### Steps to reproduce or test case

1. Start Redis
2. Run the test application (https://github.com/hmagarotto/redissonlock) with a simple locked task.
3. Force a timeout on Redis runnning a client pause command: "CLIENT PAUSE 5000"

### Redis version
4.0.10

### Redisson version
3.10.3

### Redisson configuration
Single server default

**Comment by mrniko** [comment]
Unable to reproduce. In this case lock is expired automatically by this method https://github.com/redisson/redisson/blob/1d33ebd25251aa3a4bc89187e32567507ab7f5c9/redisson/src/main/java/org/redisson/RedissonLock.java#L258 after 30 seconds by default. You can decrease this value through `Config.lockWatchdogTimeout` setting.

**Comment by hmagarotto** [comment]
Hi, thanks for your support.
In the above scenario Redisson continues to renew the TTL every 10 seconds, so the lock never expires or is removed. I will try to demonstrate better how to reproduce...

**Comment by hmagarotto** [comment]
Terminal session with test case:

https://gitcdn.link/repo/hmagarotto/8c3a4b51422e45a75f77f17d9298bbd1/raw/3dc65728fa2d79b326967f30b9a6e5be0db70acb/redisson-lock-test-term-session.svg

_recorded with [termtosvg](https://github.com/nbedos/termtosvg)_

**Comment by aawu** [comment]
same problem here https://github.com/redisson/redisson/issues/1950

**Comment by mrniko** [comment]
Fixed! Please find updated version below

[redisson-3.10.5-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/2960102/redisson-3.10.5-SNAPSHOT.jar.zip)

**Comment by aawu** [comment]
thanks for your support :)

**Comment by hmagarotto** [comment]
Thanks!
Now the lock is being removed by the Redis TTL after time expired.

**Comment by danielshama** [comment]
Hi, Still have the same issue with version 3.17.4. I'm using tryLock, after a timeout, I see that Redisson continues to renew the TTL for the same lock.

**Comment by mrniko** [comment]
@danielshama 

Please upgrade to 3.38.1 or higher. Let us know if it happens with this version.
