### ISSUE TITLE
Nullpointer exception after logout Tomcat application

### ISSUE THREAD

**Issue by wernerreuser** [redisson/redisson#2774]
**Expected behavior**

Logout without nullpointer exception

**Actual behavior**

Logout throws this exception

java.lang.NullPointerException: map value can't be null
        at org.redisson.RedissonMap.checkValue(RedissonMap.java:605)
        at org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:920)
        at org.redisson.RedissonMap.fastPut(RedissonMap.java:936)
        at org.redisson.tomcat.RedissonSession.fastPut(RedissonSession.java:239)
        at org.redisson.tomcat.RedissonSession.setAuthType(RedissonSession.java:263)
        at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:1165)
        at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:1100)
        at org.apache.catalina.authenticator.AuthenticatorBase.logout(AuthenticatorBase.java:1306)
        at org.apache.catalina.connector.Request.logout(Request.java:2765)
        at org.apache.catalina.connector.RequestFacade.logout(RequestFacade.java:1092)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:79)
        at com.sun.proxy.$Proxy60.logout(Unknown Source)
        at nl.intus.rest.ESSService.logoutInner(ESSService.java:247)
        at nl.intus.rest.ESSService.logout(ESSService.java:234)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:517)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:406)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:370)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:372)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:344)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:317)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
        at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at nl.intus.main.CorsFilter.handleNonCORS(CorsFilter.java:449)
        at nl.intus.main.CorsFilter.doFilter(CorsFilter.java:190)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:432)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce or test case**

Login using Tomcat realm and start session, logout

**Redis version**

keydb-5.3.3-1.el7.x86_64

**Redisson version**

redisson-tomcat-9-3.12.5-SNAPSHOT.jar.zip 

from : https://github.com/redisson/redisson/issues/2589

**Redisson configuration**

redisson.conf: 

singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://10.2.2.71:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

context.xml:

<Context>
        <WatchedResource>WEB-INF/web.xml</WatchedResource>

        <Manager        className="org.redisson.tomcat.RedissonSessionManager" 
                        configPath="${catalina.base}/conf/redisson.conf" 
                        readMode="REDIS" 
                        updateMode="DEFAULT" 
                        broadcastSessionEvents="false" 
                        keyPrefix="pzdproductie"
        />
</Context>

Tested with updateMode="AFTER_REQUEST" at first, changed to DEFAULT later, exception is still thrown. 

It doesn't really affect the application as it happens after destroying the session but it does fill up application logfiles.

**Comment by mrniko** [comment]
Fixed. Thanks for report

**Comment by wernerreuser** [comment]
You're amazingly fast, thanks !

Do you have a snapshot to test with ?

Best regards, 

Werner

**Comment by mrniko** [comment]
Sure, here it is!

[redisson-tomcat-9-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4634274/redisson-tomcat-9-3.12.6-SNAPSHOT.jar.zip)

**Comment by wernerreuser** [comment]
Great, I'll test it and report back to you.

**Comment by wernerreuser** [comment]
Sorry but the nullpointer still exists, exactly the same...

jar's used: 

redisson-all-3.12.4.jar
redisson-tomcat-9-3.12.6-SNAPSHOT.jar

**Comment by mrniko** [comment]
Please make sure you don't have other redisson-tomcat jars in classpath

**Comment by wernerreuser** [comment]
They're not, both jars are placed in Tomcat's lib folder, I deleted the older version.

**Comment by mrniko** [comment]
I just made sure that the check is present in jar I attached.

**Comment by wernerreuser** [comment]
And it was ?

**Comment by wernerreuser** [comment]
![image](https://user-images.githubusercontent.com/8298388/82069754-1226fe80-96d4-11ea-892b-3a1296219e27.png)

Checked my Tomcat instance as well to be sure, see image

**Comment by mrniko** [comment]
Could you get the code and build it by yourself? I have no other idea

**Comment by drcabry** [comment]
Same exception here, but on function setPrincipal()

`	java.lang.NullPointerException: map value can't be null
	at org.redisson.RedissonMap.checkValue(RedissonMap.java:605)
	at org.redisson.RedissonMap.fastPutAsync(RedissonMap.java:920)
	at org.redisson.RedissonMap.fastPut(RedissonMap.java:936)
	at org.redisson.tomcat.RedissonSession.fastPut(RedissonSession.java:252)
	at org.redisson.tomcat.RedissonSession.setPrincipal(RedissonSession.java:267)
	at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:1200)
	at org.apache.catalina.authenticator.FormAuthenticator.register(FormAuthenticator.java:365)
	at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:1134)
	at org.apache.catalina.authenticator.AuthenticatorBase.logout(AuthenticatorBase.java:1340)
	at org.apache.catalina.connector.Request.logout(Request.java:2787)
	at org.apache.catalina.connector.RequestFacade.logout(RequestFacade.java:1092)
	at javax.servlet.http.HttpServletRequestWrapper.logout(HttpServletRequestWrapper.java:344)`


could you please fix this, removing the Principal at logout?

jar's used:

redisson-all-3.13.4.jar
redisson-tomcat-9-redisson-tomcat-9-3.13.5.jar

tomcat used: 9.0.38

Thanks

**Comment by mrniko** [comment]
Fixed
