### ISSUE TITLE
redisson has a memory leak when redis cluster switched

### ISSUE THREAD

**Issue by cy1521430239** [redisson/redisson#4637]
**Expected behavior**
when redis cluster switched, The client connection to the old node should not exist in memory,   and the nodeConnections should remove the old node.
**Actual behavior**
When the redis cluster whose ip address is 192.168.3.47 is suspended, the dns switches to the redis cluster whose ip address is 192.168.3.49.
redisson keeps the redisclient that connects to the old node(192.168.3.47 ), and the connectionWatchDog keeps creating connections in the background to try to reconnect the old node.
![1666937338494](https://user-images.githubusercontent.com/56341063/198515741-42902d99-cc23-4534-9b77-903541cb9fc4.jpg)
![1666937338508](https://user-images.githubusercontent.com/56341063/198515787-c50215d8-fa47-48e4-8f68-9838874ca187.jpg)
![1666937338520](https://user-images.githubusercontent.com/56341063/198515802-8a9ab3b7-6248-4ba7-9b74-9c880f26b9be.png)

**Steps to reproduce or test case**
step one: Prepare one dns service, two redis clusters, and one application service.
step two: The application service continuously accesses redis through dns.
step three: The dns switches to another redis cluster, the simulated redis cluster is suspended, and the new redis cluster is restarted.

**Redis version**
7.0.5
**Redisson version**
3.17.7
**Redisson configuration**
         Config config = new Config();
        List<String> nodeAddresses = List.of("redis-test.com:7000").stream()
                .map(node -> MessageFormat.format("redis://{0}", node))
                .collect(Collectors.toList());
        config.useClusterServers()
                .setMasterConnectionMinimumIdleSize(3)
                .setMasterConnectionPoolSize(30)
                .setSlaveConnectionMinimumIdleSize(3)
                .setSlaveConnectionPoolSize(30)
                .setSubscriptionConnectionMinimumIdleSize(1)
                .setSlaveConnectionPoolSize(1)
                .setScanInterval(60000)
//                    .setPassword(getClusterPassword())
                .setNodeAddresses(nodeAddresses);
        return Redisson.create(config);

**Comment by mrniko** [comment]
Redisson continue to reconnect if it didn't get information form cluster topology that this node has down. Make sure that the cluster topology was properly updated.

**Comment by cy1521430239** [comment]
It performs a clusterConnectionManager shutdownEntry, but the nodeConnection MasterSlaveConnectionManager did not remove the node. I tried to remove the relevant node in the nodeConnections in the shutdownEntry method without this problem.

**Comment by cy1521430239** [comment]
The ip address obtained through domain name resolution is the IP address of the new node, and no old ip address exists.

**Comment by cy1521430239** [comment]
Thank you for your reply, redisson cluster topology information is obtained through ClusterConnectionManager.scheduleClusterChangeCheck? If this is the case, the old node information can not be obtained by the resolver in this method, then redisson should not try to reconnect the old node.

**Comment by guihuoliuying** [comment]
I have the same issue. It seems that the connection, which used to query cluster topology information, is leaked. The log about reconnecting will disappear if close the connection by using `MasterSlaveConnectionManager#disconnectNode()` right after querying cluster topology information(cluster nodes). On my observation, the leak probably happen on redis cluster switched when the connection is connected to the slave.

**Comment by mrniko** [comment]
@guihuoliuying 

Can you try build attached to this comment https://github.com/redisson/redisson/issues/4649#issuecomment-1311516290 ?

**Comment by guihuoliuying** [comment]
I ran the test with the jar presented in #4649, but the issue is still here. I capture some log grepped by "connected" or "reconnect".
![image](https://user-images.githubusercontent.com/828759/201512025-8d7cc768-f06c-4656-ac0e-be838b45f83d.png)

**Comment by mrniko** [comment]
@guihuoliuying 

This may happen due to network issues and/or multiple ips bounded to the same hostname

**Comment by guihuoliuying** [comment]
It's multiple ips bounded to the same hostname. The redis cluster is deployed in k8s and there is an operator supervise the status of redis cluster. In the logs mentioned above, I deleted a pod running a slave, then operator found and start another pod to replaced the deleted one.

**Comment by guihuoliuying** [comment]
@mrniko 
Does redisson support this scenario?

**Comment by cy1521430239** [comment]
> @guihuoliuying
> 
> Can you try build attached to this comment [#4649 (comment)](https://github.com/redisson/redisson/issues/4649#issuecomment-1311516290) ?

This seems to have solved my problem, I have no memory leaks after testing, thank you very much.

**Comment by mrniko** [comment]
Fixed! thanks for help

**Comment by mrniko** [comment]
@guihuoliuying 

Please provide more details. Which hosts you specified in Redisson configuration. And how many ips used by each hostname in a cluster.

**Comment by guihuoliuying** [comment]
Just one hostname for all ips in a cluster. 
I test with latest revision, it seems to be fixed in the first few times, but in the last time I try, the issue appear again. When I want to investigate further, the test environment was broken by my mistake. I need some time to set it up and see what happen.

**Comment by guihuoliuying** [comment]
I test with the commit '0cfc250e74132633d1415fa90506a9aae0b6e29d', the issue still appear in some cases.
**Test Environment:** As mentioned above, the redis cluster is deployed is k8s, 2 nodes, one is master, the other is slave. Application use hostname to connect cluster, the hostname is resolved to ips of nodes. An operator is used to supervise the redis cluster, if the number of nodes is dropped below 2, it will start the new pod to replace the node which is down, also it will make dns to resolve to new ip of new pod.
**Case 1:** Read mode is MASTER_SLAVE, and I delete 2 nodes. After the cluster resumed by operator, the leak didn't happen.
**Case 2:** Read mode is MASTER_SLAVE, and I delete the node which is slave. After the cluster resumed by operator, the leak still happen.
**Case 3:** Read mode is MASTER, and I delete 2 nodes. After the cluster resumed by operator, the leak still happen.

For Case 2, what about invoking disconnectNode() to delete slave while calling MasterSlaveEntry.slaveDownAsync() in ClusterConnectionManager.addRemoveSlaves()
For Case 3, what about deleting the nodes which in last partition but not in new partition right after parsePartiton

**Comment by mrniko** [comment]
@guihuoliuying 

This feature is available only in PRO version for replicated mode. https://github.com/redisson/redisson/wiki/2.-Configuration/#25-replicated-mode

**Comment by mrniko** [comment]
It's compatible with Redis setup with single master and multiple slaves. Is this your case?

**Comment by guihuoliuying** [comment]
The number of master chosen 1 is for describing the issue. I redo the test in a cluster of 3 masters and 3 slaves, in Case 2, the leak still happen.

**Comment by mrniko** [comment]
@guihuoliuying 

Can you run https://github.com/redisson/redisson/issues/4649#issuecomment-1311516290 and share logs?

**Comment by guihuoliuying** [comment]
Ok. Here is the log which filter out some sensitive data. Are these logs enough?
[server_log.txt](https://github.com/redisson/redisson/files/10104500/server_log.txt)
[redisson_config.txt](https://github.com/redisson/redisson/files/10104525/redisson_config.txt)

**Comment by guihuoliuying** [comment]
@mrniko Does it help? Need more logs?

**Comment by mrniko** [comment]
@guihuoliuying 

Try to set `slaveConnectionPoolSize = 20` and `masterConnectionPoolSize = 20` and `subscriptionConnectionPoolSize = 20`
